name: "Deployment"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  workflow:
    uses: ungms/.github/.github/workflows/docker.yml@main
    permissions:
      contents: read
      packages: write
    
    secrets: inherit
    with:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
        
        PORTAINER: true
        URL: "https://.unnamed.games"
